# image: ubuntu:16.04
variables: 
  CI_DEBUG_TRACE: "true"
  # GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs openssh-client
  - eval $(ssh-agent -s)
  - chmod 0600 id_rsa
  - ssh-add id_rsa
  - 'test -d ~/.ssh || mkdir -p ~/.ssh'
  - 'test -f  /.dockerenv && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
demo:
  script:
    - export 
    - 'git clone --mirror git@github.com:DanielHauschildt/gitlab-integration.git github'
    - 'cd github'
    - 'git remote add --mirror=push gitlab git@gitlab.9elements.com:daniel.hauschildt/gitlab-integration.git || true'
    - 'git push gitlab'