# image: ubuntu:16.04
variables: 
  CI_DEBUG_TRACE: "true"
  # GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs openssh-client
  - eval $(ssh-agent -s)
  - chmod 0600 id_rsa
  - ssh-add id_rsa
  - 'test -d ~/.ssh || mkdir -p ~/.ssh'
  - 'test -f  /.dockerenv && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
demo:
  script:
    - export 
    - 'git remote add github git@github.com:DanielHauschildt/gitlab-integration.git || true'
    - 'git remote set-url  --push github ""'
    - 'git fetch --all' 
    - 'for remote in `git branch -r `; do git branch --track $remote; done || for remote in `git branch -r `; do git checkout $remote ; git pull; done'
    - 'git push --progress --follow-tags --all'
